import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LandingPgRB from "@/pages/Rulebook/LandingPgRB";
import LandingPgS from "@/pages/Secretariat/LandingPgS"
import LandingPgF from "@/pages/Faqs/LandingPgF"
import LandingPgH from "@/pages/Home/LandingPgH"
import HomePg from "@/pages/Home/HomePg"
import Gallery from "@/pages/Gallery/Gallery";
import Faqs from "@/pages/Faqs/Faqs";
// import Committee from "@/pages/Committees/Committee";
import Committee from "@/pages/Committees/Committee";
import RuleBook from "@/pages/Rulebook/RuleBook";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <LandingPgH/>
        {/* <LandingPgRB /> */}
        <LandingPgS/>
        <LandingPgF/>
        <HomePg/>
        <Committee/>
        <Gallery/>  
        <RuleBook/>
        {/* <Faqs/> */}
        <Footer />
      </body>
    </html>
  );
}
