const cardData = {
  Secretariat: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 6,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 7,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      // Add more members as needed
    ],
  },
  Technical: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Sponsorship: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Decoration: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Design: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Content: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Media: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Hospitality: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
};

export default cardData;
