const cardData = {
  Secretariat: {
    members: [
      {
        id: 1,
        name: 'Rahul Xavier',
        designation: 'Chief Advisor',
        linkedin: 'https://www.linkedin.com/in/rahul-xavier-426773239',
        instagram: 'https://www.instagram.com/rahul_xvr',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679909/profile%20pictures/Rahul%20Xavier.jpg',
      },
      {
        id: 2,
        name: 'Mirza YS Baig',
        designation: 'Secretary General',
        linkedin: 'https://www.linkedin.com/in/mirza-baig-nitp',
        instagram: 'https://www.instagram.com/mirzathedreamers',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723299653/profile%20pictures/Mirza_rrhter.jpg',
      },
      {
        id: 3,
        name: 'Aniket Kumar',
        designation: 'Director General',
        linkedin: 'https://www.linkedin.com/in/aniket-kumar-142689219',
        instagram: 'https://www.instagram.com/_aniket725_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298124/profile%20pictures/Aniket_ezjqqx.jpg',
      },
      {
        id: 4,
        name: 'Satyam',
        designation: 'Head of OC',
        linkedin: 'https://www.linkedin.com/in/satyam-kumar-434165250',
        instagram: 'https://www.instagram.com/Satyamk1345',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719686810/profile%20pictures/satyam%20kumar%282%29.jpg',
      },
      {
        id: 5,
        name: 'Bhawna',
        designation: 'Co-Head of OC',
        linkedin: 'https://www.linkedin.com/in/bhawna-roy-164946257',
        instagram: 'https://www.instagram.com/bhawna.bhardwaj22',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680116/profile%20pictures/bhawna%20roy.jpg',
      },
      {
        id: 6,
        name: 'Aditya ',
        designation: 'Head of Executive Board',
        linkedin: 'https://www.linkedin.com/in/aditya-kumar-7bb54b257/',
        instagram: 'https://www.instagram.com/adityakumar.393',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679797/profile%20pictures/aditya%20kumar.jpg',
      },
      {
        id: 7,
        name: 'Reeya ',
        designation: 'Co-Head of Executive Board',
        linkedin: 'https://www.linkedin.com/in/reeya-ranjan-bb963830a',
        instagram: 'https://www.instagram.com/reeyaranjan',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679712/profile%20pictures/reeya%20ranjan.jpg',
      },
      {
        id: 8,
        name: 'Lakshya',
        designation: 'Head of Delegates Affairs',
        linkedin: 'https://www.linkedin.com/in/lakshya-parashar-65156b301',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298124/profile%20pictures/Lakshya_c0j9gj.jpg',
      },
      {
        id: 9,
        name: 'Shikha ',
        designation: 'Co-Head of Delegates Affairs',
        linkedin: 'https://www.linkedin.com/in/shikha-thakur-8028a7258/',
        instagram: 'https://www.instagram.com/nebula_k05',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680104/profile%20pictures/SHIKHA%20THAKUR.jpg',
      },
      {
        id: 10,
        name: 'Mayank ',
        designation: 'USG PR & Marketing Head',
        linkedin: 'https://www.linkedin.com/in/mayank-harsh-61704b278',
        instagram: 'https://www.instagram.com/mayank._.harsh',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679589/profile%20pictures/mayank%20harsh.jpg',
      },
      {
        id: 11,
        name: 'Kshitije ',
        designation: 'USG PR & Marketing Co-Head',
        linkedin: 'https://www.linkedin.com/in/kshitijekvs',
        instagram: 'https://www.instagram.com/Kshitijesingh_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679797/profile%20pictures/KSHITIJE%20VINAY%20SINGH.jpg',
      },
      {
        id: 12,
        name: 'Dipesh ',
        designation: 'USG Creative Head',
        linkedin: 'https://www.linkedin.com/in/dipesh-singh-0225891ba',
        instagram: 'https://www.instagram.com/di.pesh279',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719725403/profile%20pictures/Dipesh_Kumar_adhcjo.jpg',
      },
      {
        id: 13,
        name: 'Bhavya',
        designation: 'USG Creative Co-Head',
        linkedin: 'https://www.linkedin.com/in/bhavya-sinha-',
        instagram: 'https://www.instagram.com/bhav_yeaaah',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680084/profile%20pictures/BHAVYA%20SINHA.jpg',
      },
      {
        id: 14,
        name: 'Vani ',
        designation: 'USG Content Head',
        linkedin: 'https://www.linkedin.com/in/vani-kumari-45645b245',
        instagram: 'https://www.instagram.com/vanisingh_2701/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719684557/profile%20pictures/VANI%20SINGH.jpg',
      },
      {
        id: 15,
        name: 'Supriya',
        designation: 'USG Content Co-Head',
        linkedin: 'https://www.linkedin.com/in/supriya-kumari-1021a7258',
        instagram: 'https://www.instagram.com/supriya_sharma_568',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680132/profile%20pictures/SUPRIYA%20KUMARI.jpg',
      },
      {
        id: 16,
        name: 'Utsav ',
        designation: 'USG Design Head',
        linkedin: 'https://www.linkedin.com/in/utsav-thakur-960760294',
        instagram: 'https://www.instagram.com/thakur_utsav_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723304102/profile%20pictures/UTSAV_THAKUR_dysodt.jpg',
      },
      {
        id: 17,
        name: 'Chirag',
        designation: 'USG Design Co-Head',
        linkedin: 'https://www.linkedin.com/in/chirag-kumar-rai-bbb009271',
        instagram: 'https://www.instagram.com/chirag.rai31',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719725607/profile%20pictures/Rai_Chirag_Kumar_jucwst.jpg',
      },
      {
        id: 18,
        name: 'Neeraj',
        designation: 'USG Media Head',
        linkedin: 'https://www.linkedin.com/in/neeraj-kumar-96657330a/',
        instagram: 'https://www.instagram.com/neerajk1617',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723304097/profile%20pictures/NEERAJ_KUMAR_cmesya.jpg',
      },
      {
        id: 19,
        name: 'Anshu ',
        designation: 'USG Media Co-Head',
        linkedin: 'https://www.linkedin.com/in/anshu-kumari-a32936257',
        instagram: 'https://www.instagram.com/___anshukumari___',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680096/profile%20pictures/ANSHU%20KUMARI.jpg',
      },
      {
        id: 20,
        name: 'Manaswini',
        designation: 'USG Social Media Head',
        linkedin: 'https://www.linkedin.com/in/manaswini-patil-981b03294',
        instagram: 'https://www.instagram.com/manaswini_patil_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679796/profile%20pictures/PATIL%20MANASWINI%20RAVINDRA.jpg',
      },
      {
        id: 21,
        name: 'Aishwarya',
        designation: 'USG Social Media Co-Head',
        linkedin: 'https://www.linkedin.com/in/aishwarya-adak-573605237',
        instagram: 'https://www.instagram.com/parlegtoyourchai',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679908/profile%20pictures/AISHWARYA%20ADAK.jpg',
      },
      {
        id: 22,
        name: 'Shubham ',
        designation: 'USG Web Head',
        linkedin: 'https://www.linkedin.com/in/shubham-tiwari-966223253',
        instagram: 'https://www.instagram.com/shubham_tiwarii05/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679916/profile%20pictures/Shubham%20Tiwari.jpg',
      },
      {
        id: 23,
        name: 'Shradha ',
        designation: 'USG Web Co-Head',
        linkedin: 'https://www.linkedin.com/in/shradha-jha-68797621b',
        instagram: 'https://www.instagram.com/shradhajha06',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719686809/profile%20pictures/shradha%20jha.jpg',
      },
      {
        id: 24,
        name: 'Nilabh ',
        designation: 'USG Technical Head',
        linkedin: 'https://www.linkedin.com/in/nilabh-mishra-383788257',
        instagram: 'https://www.instagram.com/nilabh_mishra',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679796/profile%20pictures/nilabh%20mishra.jpg',
      },
      {
        id: 25,
        name: 'Lalit',
        designation: 'USG Technical Co-Head',
        linkedin: 'https://www.linkedin.com/in/lalit-kumar-b18a98284',
        instagram: 'https://www.instagram.com/maurya_lalit_7',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680099/profile%20pictures/LALIT%20KUMAR.jpg',
      },
      {
        id: 26,
        name: 'Akash',
        designation: 'USG Logistics Head',
        linkedin: 'https://www.linkedin.com/in/akashpatelsingh1',
        instagram: 'https://www.instagram.com/akash.nitp',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719684480/profile%20pictures/AKASH%20PATEL%20SINGH.jpg',
      },
      {
        id: 27,
        name: 'Anish',
        designation: 'USG Logistics Co-Head',
        linkedin: '',
        instagram: 'https://www.instagram.com/Anish_Anand_yadavanshi',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680087/profile%20pictures/ANISH%20KUMAR.jpg',
      },
      // Add more members as needed
    ],
  },
  Seniors: {
    members: [
      {
        id: 1,
        name: 'Aman Gupta',
        designation: 'Advisory',
        linkedin: 'https://www.linkedin.com/in/aman-gupta-3726521b4',
        instagram: 'https://www.instagram.com/itz_aman506',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719685003/profile%20pictures/AMAN%20GUPTA.jpg',
      },
      {
        id: 2,
        name: "Alankrita Singh",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/alankrita-singh-2a13b6260",
        instagram: "https://www.instagram.com/alankrita_singh0520",
        image: "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679914/profile%20pictures/ALANKRITA%20SINGH.jpg",
      },
      {
        id: 3,
        name: "Pawni Chauhan",
        designation: "Advisory",
        linkedin: "https://linkedin.com/in/pawni-chauhan-95b181249",
        instagram: "https://www.instagram.com/pawnichauhan7",
        image:
          "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679799/profile%20pictures/PAWNI%20CHAUHAN.jpg",
      },
      {
        id: 4,
        name: "Harshali",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/harshali-59564b228",
        instagram: "https://www.instagram.com/",
        image:
          "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680111/profile%20pictures/HARSHALI.jpg",
      },
      {
        id: 5,
        name: "Harsh Vardhan",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/harsh-vardhan-4354b1237/",
        instagram: "https://www.instagram.com/ig_harsh.vardhan",
        image:
          "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679798/profile%20pictures/Harsh%20Vardhan.jpg",
      },
      {
        id: 6,
        name: "Shalvee Kumari",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/shalvee0920",
        instagram: "https://www.instagram.com/shalvee_20",
        image:
          "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679911/profile%20pictures/shalvee%20kumari.jpg",
      },    
      {
        id: 7,
        name: "Shivani",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/shivani-raj-59b798257",
        instagram: "https://www.instagram.com/Shivaniraj4683",
        image:
          "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719682009/profile%20pictures/Shivani%20Raj.jpg",
      },
      {
        id: 8,
        name: "Rohan Shetty",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/rohan1704",
        instagram: "https://www.instagram.com/shetty._.rohan",
        image: "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679712/profile%20pictures/Rohan%20Shetty.jpg",
      },
      {
        id: 9,
        name: "Arun Singh",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/arun-singh-1a0b25225",
        instagram: "https://www.instagram.com/arunsingh_.08/",
        image: "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680095/profile%20pictures/ARUN%20SINGH.png",
      },
      {
        id: 10,
        name: "Aishwarya Pandit",
        designation: "Advisory",
        linkedin: "https://www.linkedin.com/in/aishwarya-pandit-176567234",
        instagram: "https://www.instagram.com/yours.aishwarya_",
        image: "https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680116/profile%20pictures/AISHSWARYA%20PANDIT.jpg",

      },
      
    ],
  },
  Technical: {
    members: [
      {
        id: 1,
        name: 'Aakash',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aakash-tiwari-in',
        instagram: 'https://www.instagram.com/tiwariji.789/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680107/profile%20pictures/Aakash%20tiwari.jpg',
      },
      {
        id: 2,
        name: 'Saim',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/saim-jawed-6a8766294',
        instagram: 'https://www.instagram.com/s._aim_jawed',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1720505709/profile%20pictures/SaimJawed.jpg',
      },
      {
        id: 3,
        name: 'Akanksha',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/akanksha-nigam-5a70012ab',
        instagram: 'https://www.instagram.com/akankshanigam217',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298123/profile%20pictures/Akanksha_Nigam_j2ck03.jpg',
      },
      {
        id: 4,
        name: 'Rupak',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/rupak-parashar-355053317',
        instagram: 'https://www.instagram.com/rajrupakparashar.47',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723297321/profile%20pictures/Rupak%20Parashar1.jpg',
      },
      {
        id: 5,
        name: 'Anurag',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/anurag-kumar-14ba2828b',
        instagram: 'https://www.instagram.com/tiwary_anuragg',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723297312/profile%20pictures/Anurag%20Tiwari.jpg',
      },
      {
        id: 6,
        name: 'Ratnesh',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ratnesh-anand-nitp/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298123/profile%20pictures/Ratnesh_Anand_ltbcxq.jpg',
      },
    ],
  },
  Sponsorship: {
    members: [
      {
        id: 1,
        name: 'Akanksha',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/akanksha-nigam-5a70012ab/',
        instagram: 'https://www.instagram.com/akankshanigam217',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298123/profile%20pictures/Akanksha_Nigam_j2ck03.jpg',
      },
      {
        id: 2,
        name: 'Ratnesh',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ratnesh-anand-nitp/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298123/profile%20pictures/Ratnesh_Anand_ltbcxq.jpg',
      },
      
      {
        id: 3,
        name: 'Suhana',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/suhana-singh-659012290/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298614/profile%20pictures/Suhana_egjtdu.jpg',
      },
      {
        id: 4,
        name: 'Kaushikee',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/kaushikee-kashyap-891a55314/',
        instagram: 'https://www.instagram.com/kaushikee_k/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679795/profile%20pictures/KAUSHIKEE%20KASHYAP.jpg',
      },
      {
        id: 5,
        name: 'Saim ',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/saim-jawed-6a8766294/',
        instagram: 'https://www.instagram.com/s._aim_jawed/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1720505709/profile%20pictures/SaimJawed.jpg',
      },
      {
        id: 6,
        name: 'Nikita',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/nikita-pant-852806280/',
        instagram: 'https://www.instagram.com/nikitapant9/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680115/profile%20pictures/nikita%20pant.jpg',
      },
      {
        id: 7,
        name: 'Ayushi',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ayushi-shukla-55021928b/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680114/profile%20pictures/ayushi%20shukla.jpg',
      },
      {
        id: 8,
        name: 'Rupak',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/rupak-parashar-355053317/',
        instagram: 'https://www.instagram.com/rajrupakparashar.47/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723297321/profile%20pictures/Rupak%20Parashar1.jpg',
      },
      {
        id: 9,
        name: 'Anurag',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/anurag-kumar-14ba2828b/',
        instagram: 'https://www.instagram.com/tiwary_anuragg/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723297312/profile%20pictures/Anurag%20Tiwari.jpg',
      },
      {
        id: 10,
        name: 'Harsh',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/harsh-dwivedi-4b9bb9289/',
        instagram: 'https://www.instagram.com/harsh_ackreman/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723303571/profile%20pictures/harsh_sa6n5g.jpg',
      }
    ],
  },
  Decoration: {
    members: [
      {
        id: 1,
        name: 'Adarsh',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/adarsh-kumar-dubey-748024290/',
        instagram: 'https://www.instagram.com/dubeyadarsh.028/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679795/profile%20pictures/Adarsh%20Dubey.jpg',
      },
      {
        id: 2,
        name: 'Akanksha',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/akanksha-nigam-5a70012ab/',
        instagram: 'https://www.instagram.com/akankshanigam217',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298123/profile%20pictures/Akanksha_Nigam_j2ck03.jpg',
      },
      {
        id: 3,
        name: 'Anamika',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/anamika-a6457828b/',
        instagram: 'https://www.instagram.com/anamikaa.7/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719686809/profile%20pictures/anamika%20kumari.jpg',
      },
      {
        id: 4,
        name: 'Damini',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/damini-kumari-a0a098282/',
        instagram: 'https://www.instagram.com/da_snowmin/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680088/profile%20pictures/DAMINI%20KUMARI.jpg',
      },
      {
        id: 5,
        name: 'Krish',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/krish-kumar-sinha-a9b422246/',
        instagram: 'https://www.instagram.com/krish.dripss_/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680106/profile%20pictures/gdmndbkqs4pvm1dd8xay.jpg',
      },
      {
        id: 6,
        name: 'Madhumista',
        designation: 'Member',
        linkedin: ' ',
        instagram: 'https://www.instagram.com/jfoyrangggg/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680105/profile%20pictures/madhumista.jpg',
      },
      {
        id: 7,
        name: 'Shreyashi',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/shreyashi-chatterjee-5b684127b/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679798/profile%20pictures/SHREYASHI%20CHATTERJEE.jpg',
      }
    ],
  },
  Design: {
    members: [
      
  
      {
        id: 1,

        name: 'Nicky',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/nicky-kumari-7a57312b6',
        instagram: 'https://www.instagram.com/nickyk2004?igsh=Z2tyaXhxNTkzeHE2',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679600/profile%20pictures/NICKY%20KUMARI.jpg',
      },
      
      {
        id: 2,
        name: 'Krish',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/krish-kumar-sinha-a9b422246',
        instagram: 'https://www.instagram.com/krish.dripss_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680106/profile%20pictures/gdmndbkqs4pvm1dd8xay.jpg',
      },
      {
        id: 3,
        name: 'Sanchita',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/sanchita-jha?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
        instagram: 'https://www.instagram.com/sanchitaj_04/?igsh=MWF0anZucWRqY256cA%3D%3D',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680099/profile%20pictures/SANCHITA%20JHA.jpg',
      },
      {
        id: 4,
        name: 'Shreyashi',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/shreyashi-chatterjee-5b684127b',
        instagram: 'https://www.instagram.com/shrey_ashi03',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679798/profile%20pictures/SHREYASHI%20CHATTERJEE.jpg',
      },
      {
        id: 5,
        name: 'Abhay',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/abhay-ravidas-a9933b233',
        instagram: 'https://www.instagram.com/nitp_abhay',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719727544/profile%20pictures/Abhay_Ravidas_nxklmk.jpg',
      },
      {
        id: 6,
        name: 'Om',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/om-vats-6aab58280',
        instagram: 'https://www.instagram.com/omvats09',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298122/profile%20pictures/Om_Vats_h7jra0.jpg',
      },
    ],
  },
  Content: {
    members: [
      {
        id: 1,
        name: 'Moupiya',
        designation: 'Member',
        linkedin: ' ',
        instagram: 'https://www.instagram.com/its_mou2022piya/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298619/profile%20pictures/Moupiya_wtbcrf.jpg',
      },
      {
        id: 2,
        name: 'Suhana',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/suhana-singh-659012290/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298614/profile%20pictures/Suhana_egjtdu.jpg',
      },
      {
        id: 3,
        name: 'Ayushi',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ayushi-shukla-55021928b/',
        instagram: ' ',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680114/profile%20pictures/ayushi%20shukla.jpg',
      },
      {
        id: 4,
        name: 'Kaushikee',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/kaushikee-kashyap-891a55314/',
        instagram: 'https://www.instagram.com/kaushikee_k/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679795/profile%20pictures/KAUSHIKEE%20KASHYAP.jpg',
      },
      {

        id: 5,
        name: 'Sanchita',

        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/sanchita-jha/',
        instagram: 'https://www.instagram.com/sanchitaj_04/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680099/profile%20pictures/SANCHITA%20JHA.jpg',
      },
      {
        id: 6,
        name: 'Om',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/om-vats-6aab58280/',
        instagram: 'https://www.instagram.com/omvats09/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723298122/profile%20pictures/Om_Vats_h7jra0.jpg',
      },
      {
        id: 7,
        name: 'Harsh',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/harsh-dwivedi-4b9bb9289/',
        instagram: 'https://www.instagram.com/harsh_ackreman/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1723303571/profile%20pictures/harsh_sa6n5g.jpg',
      },
      {
        id: 8,
        name: 'Supriya',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/supriya-raj-0128a4295/',
        instagram: 'https://www.instagram.com/supriyaraj5073/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680112/profile%20pictures/SUPRIYA%20RAJ.jpg',
      },
    ],
  },
  Media: {
    members: [
      
      {
        id: 1,

        name: 'Abhay',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/abhay-ravidas-a9933b233',
        instagram: 'https://www.instagram.com/nitp_abhay',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719727544/profile%20pictures/Abhay_Ravidas_nxklmk.jpg',
      },
      {
        id: 2,
        name: 'Krish',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/krish-kumar-sinha-a9b422246',
        instagram: 'https://www.instagram.com/krish.dripss_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680106/profile%20pictures/gdmndbkqs4pvm1dd8xay.jpg',
      },
      {
        id: 3,
        name: 'Aniket',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aniket-kumar-142689219',
        instagram: 'https://www.instagram.com/_aniket725_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680100/profile%20pictures/ANIKET%20KUMAR%281%29.jpg',
      },
    ],
  },
  Hospitality: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
};

export default cardData;
