const cardData = {
  Secretariat: {
    members: [
      {
        id: 1,
        name: 'Rahul Xavier',
        designation: 'Chief Advisor',
        linkedin: 'https://www.linkedin.com/in/rahul-xavier-426773239',
        instagram: 'https://www.instagram.com/rahul_xvr',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679909/profile%20pictures/Rahul%20Xavier.jpg',
      },
      {
        id: 2,
        name: 'Mirza YS Baig',
        designation: 'Secretary General',
        linkedin: 'https://www.linkedin.com/in/mirza-baig-nitp',
        instagram: 'https://www.instagram.com/mirzathedreamers',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679915/profile%20pictures/MIRZA%20BAIG.jpg',
      },
      {
        id: 3,
        name: 'Aniket Kumar',
        designation: 'Director General',
        linkedin: 'https://www.linkedin.com/in/aniket-kumar-142689219',
        instagram: 'https://www.instagram.com/_aniket725_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679912/profile%20pictures/ANIKET%20KUMAR.png',
      },
      {
        id: 4,
        name: 'Satyam',
        designation: 'Head of OC',
        linkedin: 'https://www.linkedin.com/in/satyam-kumar-434165250',
        instagram: 'https://www.instagram.com/Satyamk1345',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679914/profile%20pictures/SATYAM%20KUMAR.jpg',
      },
      {
        id: 5,
        name: 'Bhawna Roy',
        designation: 'Co-Head of OC',
        linkedin: 'https://www.linkedin.com/in/bhawna-roy-164946257',
        instagram: 'https://www.instagram.com/bhawna.bhardwaj22',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680116/profile%20pictures/bhawna%20roy.jpg',
      },
      {
        id: 6,
        name: 'Aditya Kumar',
        designation: 'Head of Executive Board',
        linkedin: 'https://www.linkedin.com/in/aditya-kumar-7bb54b257/',
        instagram: 'https://www.instagram.com/adityakumar.393',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679797/profile%20pictures/aditya%20kumar.jpg',
      },
      {
        id: 7,
        name: 'Reeya Ranjan',
        designation: 'Co-Head of Executive Board',
        linkedin: 'https://www.linkedin.com/in/reeya-ranjan-bb963830a',
        instagram: 'https://www.instagram.com/reeyaranjan',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679712/profile%20pictures/reeya%20ranjan.jpg',
      },
      {
        id: 8,
        name: 'Lakshya Parashar',
        designation: 'Head of Delegates Affairs',
        linkedin: 'https://www.linkedin.com/in/lakshya-parashar-65156b301',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679909/profile%20pictures/LAKSHAY%20PARASHAR.png',
      },
      {
        id: 9,
        name: 'Shikha Thakur',
        designation: 'Co-Head of Delegates Affairs',
        linkedin: 'https://www.linkedin.com/in/shikha-thakur-8028a7258/',
        instagram: 'https://www.instagram.com/nebula_k05',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680104/profile%20pictures/SHIKHA%20THAKUR.jpg',
      },
      {
        id: 10,
        name: 'Mayank Harsh',
        designation: 'USG PR & Marketing Head',
        linkedin: 'https://www.linkedin.com/in/mayank-harsh-61704b278',
        instagram: 'https://www.instagram.com/mayank._.harsh',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679589/profile%20pictures/mayank%20harsh.jpg',
      },
      {
        id: 11,
        name: 'Kshitije Vinay Singh',
        designation: 'USG PR & Marketing Co-Head',
        linkedin: 'https://www.linkedin.com/in/kshitijekvs',
        instagram: 'https://www.instagram.com/Kshitijesingh_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679797/profile%20pictures/KSHITIJE%20VINAY%20SINGH.jpg',
      },
      {
        id: 12,
        name: 'Dipesh Kumar Singh',
        designation: 'USG Creative Head',
        linkedin: 'https://www.linkedin.com/in/dipesh-singh-0225891ba',
        instagram: 'https://www.instagram.com/di.pesh279',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719725403/profile%20pictures/Dipesh_Kumar_adhcjo.jpg',
      },
      {
        id: 13,
        name: 'Bhavya Sinha',
        designation: 'USG Creative Co-Head',
        linkedin: 'https://www.linkedin.com/in/bhavya-sinha-',
        instagram: 'https://www.instagram.com/bhav_yeaaah',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680084/profile%20pictures/BHAVYA%20SINHA.jpg',
      },
      {
        id: 14,
        name: 'Vani Kumari',
        designation: 'USG Content Head',
        linkedin: 'https://www.linkedin.com/in/vani-kumari-45645b245',
        instagram: 'https://www.instagram.com/vanisingh_2701/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719684557/profile%20pictures/VANI%20SINGH.jpg',
      },
      {
        id: 15,
        name: 'Supriya Kumari',
        designation: 'USG Content Co-Head',
        linkedin: 'https://www.linkedin.com/in/supriya-kumari-1021a7258',
        instagram: 'https://www.instagram.com/supriya_sharma_568',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680132/profile%20pictures/SUPRIYA%20KUMARI.jpg',
      },
      {
        id: 16,
        name: 'Utsav Thakur',
        designation: 'USG Design Head',
        linkedin: 'https://www.linkedin.com/in/utsav-thakur-960760294',
        instagram: 'https://www.instagram.com/thakur_utsav_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680104/profile%20pictures/UTSAV%20THAKUR.jpg',
      },
      {
        id: 17,
        name: 'Rai Chirag Kumar',
        designation: 'USG Design Co-Head',
        linkedin: 'https://www.linkedin.com/in/chirag-kumar-rai-bbb009271',
        instagram: 'https://www.instagram.com/chirag.rai31',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719725607/profile%20pictures/Rai_Chirag_Kumar_jucwst.jpg',
      },
      {
        id: 18,
        name: 'Neeraj Kumar',
        designation: 'USG Media Head',
        linkedin: 'https://www.linkedin.com/in/neeraj-kumar-96657330a/',
        instagram: 'https://www.instagram.com/neerajk1617',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680088/profile%20pictures/NEERAJ%20KUMAR.jpg',
      },
      {
        id: 19,
        name: 'Anshu Kumari',
        designation: 'USG Media Co-Head',
        linkedin: 'https://www.linkedin.com/in/anshu-kumari-a32936257',
        instagram: 'https://www.instagram.com/___anshukumari___',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680096/profile%20pictures/ANSHU%20KUMARI.jpg',
      },
      {
        id: 20,
        name: 'Manaswini Patil',
        designation: 'USG Social Media Head',
        linkedin: 'https://www.linkedin.com/in/manaswini-patil-981b03294',
        instagram: 'https://www.instagram.com/manaswini_patil_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679796/profile%20pictures/PATIL%20MANASWINI%20RAVINDRA.jpg',
      },
      {
        id: 21,
        name: 'Aishwarya Pandit',
        designation: 'USG Social Media Co-Head',
        linkedin: 'https://www.linkedin.com/in/aishwarya-pandit-176567234',
        instagram: 'https://www.instagram.com/yours.aishwarya_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680116/profile%20pictures/AISHSWARYA%20PANDIT.jpg',
      },
      {
        id: 22,
        name: 'Shubham Tiwari',
        designation: 'USG Web Head',
        linkedin: 'https://www.linkedin.com/in/shubham-tiwari-966223253',
        instagram: 'https://www.instagram.com/shubham_tiwarii05/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679916/profile%20pictures/Shubham%20Tiwari.jpg',
      },
      {
        id: 23,
        name: 'Shradha Jha',
        designation: 'USG Web Co-Head',
        linkedin: 'https://www.linkedin.com/in/shradha-jha-68797621b',
        instagram: 'https://www.instagram.com/shradhajha06',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719686809/profile%20pictures/shradha%20jha.jpg',
      },
      {
        id: 24,
        name: 'Nilabh Mishra',
        designation: 'USG Technical Head',
        linkedin: 'https://www.linkedin.com/in/nilabh-mishra-383788257',
        instagram: 'https://www.instagram.com/nilabh_mishra',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679796/profile%20pictures/nilabh%20mishra.jpg',
      },
      {
        id: 25,
        name: 'Lalit Kumar',
        designation: 'USG Technical Co-Head',
        linkedin: 'https://www.linkedin.com/in/lalit-kumar-b18a98284',
        instagram: 'https://www.instagram.com/maurya_lalit_7',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680099/profile%20pictures/LALIT%20KUMAR.jpg',
      },
      {
        id: 26,
        name: 'Akash Patel Singh',
        designation: 'USG Logistics Head',
        linkedin: 'https://www.linkedin.com/in/akashpatelsingh1',
        instagram: 'https://www.instagram.com/akash.nitp',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719684480/profile%20pictures/AKASH%20PATEL%20SINGH.jpg',
      },
      {
        id: 27,
        name: 'Anish Kumar',
        designation: 'USG Logistics Co-Head',
        linkedin: '',
        instagram: 'https://www.instagram.com/Anish_Anand_yadavanshi',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680087/profile%20pictures/ANISH%20KUMAR.jpg',
      },
      // Add more members as needed
    ],
  },
  Seniors: {
    members: [
      {
        id: 1,
        name: 'Aman Gupta',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aman-gupta-3726521b4',
        instagram: 'https://www.instagram.com/itz_aman506',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719685003/profile%20pictures/AMAN%20GUPTA.jpg',
      },
      {
        id: 2,
        name: 'Ronak Das',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ronak-dass-682b56270/',
        instagram: 'https://www.instagram.com/mrronak_d/#',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719727411/profile%20pictures/Ronak_Das_bsj0fx.jpg',
      },
      {
        id: 3,
        name: 'Jeevan Pamidipati',
        designation: 'Member',
        linkedin: '',
        instagram: 'https://www.instagram.com/zeevan0863',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680110/profile%20pictures/Pamidipati%20Jeevan.jpg',
      },
      {
        id: 4,
        name: 'Nicky Kumari',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/nicky-kumari-7a57312b6',
        instagram: '',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679600/profile%20pictures/NICKY%20KUMARI.jpg',
      },
      {
        id: 5,
        name: 'Kiran Saini',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/kiran7saini9',
        instagram: '',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679800/profile%20pictures/KIRAN%20SAINI.jpg',
      },
      {
        id: 6,
        name: 'Kushagra',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/kushagra-singh-888996258',
        instagram: 'https://www.instagram.com/the_kushagra_singhh',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719727652/profile%20pictures/Kushagra_k1j0dw.jpg',
      },
      {
        id: 7,
        name: 'Aditi Jayesh Rao',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aditi-jayesh-rao-a506a818b',
        instagram: 'https://www.instagram.com/_nabii1.14_',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719727484/profile%20pictures/Aditi_Jayesh_Rao_mcchf4.png',
      },
      {
        id: 8,
        name: 'Rajnandini Roy',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/rajnandini-roy-031a61261',
        instagram: '',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679711/profile%20pictures/rajnandini%20roy.jpg',
      },
      {
        id: 9,
        name: 'Ritika Kumari',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/ritika-kumari-bb4705258',
        instagram: 'https://www.instagram.com/ritikakumari_chaurasia1234',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680103/profile%20pictures/RITIKA%20KUMARI.jpg',
      },
      {
        id: 10,
        name: 'Aishwarya Adak',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aishwarya-adak-573605237',
        instagram: 'https://www.instagram.com/parlegtoyourchai',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679908/profile%20pictures/AISHWARYA%20ADAK.jpg',
      },
      {
        id: 11,
        name: 'Dristi Upadhyay',
        designation: 'Member',
        linkedin: '',
        instagram: 'https://www.instagram.com/drishtiupadhyay',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719679800/profile%20pictures/DRISTI%20UPADHYAY.jpg',
      },
    ],
  },
  Technical: {
    members: [
      {
        id: 1,
        name: 'Aakash Tiwari',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/aakash-tiwari-in',
        instagram: 'https://www.instagram.com/tiwariji.789/',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680107/profile%20pictures/Aakash%20tiwari.jpg',
      },
      {
        id: 2,
        name: 'Saim Javed',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/saim-jawed-6a8766294',
        instagram: 'https://www.instagram.com/s._aim_jawed',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1720505709/profile%20pictures/SaimJawed.jpg',
      },
      {
        id: 3,
        name: 'Akansha Nigam',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/akanksha-nigam-5a70012ab',
        instagram: 'https://www.instagram.com/akankshanigam217',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680084/profile%20pictures/AKANKSHA%20NIGAM.jpg',
      },
      {
        id: 4,
        name: 'Rupak Parashar',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/rupak-parashar-355053317',
        instagram: 'https://www.instagram.com/rajrupakparashar.47',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680112/profile%20pictures/rupak%20parashar.jpg',
      },
      {
        id: 5,
        name: 'Anurag Kumar',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/anurag-kumar-14ba2828b',
        instagram: 'https://www.instagram.com/tiwary_anuragg',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719680113/profile%20pictures/ANURAG%20KUMAR.jpg',
      },
      {
        id: 6,
        name: 'Om Vats',
        designation: 'Member',
        linkedin: 'https://www.linkedin.com/in/om-vats-6aab58280',
        instagram: 'https://www.instagram.com/omvats09',
        image: 'https://res.cloudinary.com/dnbutfdy7/image/upload/v1719829548/profile%20pictures/Om_Vats.jpg',
      },
    ],
  },
  Sponsorship: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Decoration: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Design: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Content: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Media: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
  Hospitality: {
    members: [
      {
        id: 1,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 2,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
      {
        id: 3,
        name: 'Sam Wilson',
        designation: 'Secretary',
        linkedin: 'https://www.linkedin.com/in/samwilson',
        instagram: 'https://www.instagram.com/samwilson',
        image: 'sam_wilson.jpg',
      },
      {
        id: 4,
        name: 'John Doe',
        designation: 'President',
        linkedin: 'https://www.linkedin.com/in/johndoe',
        instagram: 'https://www.instagram.com/johndoe',
        image: 'john_doe.jpg',
      },
      {
        id: 5,
        name: 'Jane Smith',
        designation: 'Vice President',
        linkedin: 'https://www.linkedin.com/in/janesmith',
        instagram: 'https://www.instagram.com/janesmith',
        image: 'jane_smith.jpg',
      },
    ],
  },
};

export default cardData;
